import { readFileSync } from "fs";
import { join } from "path";

/**
 * GET /api/docs
 * Returns the OpenAPI 3.0 specification generated by scripts/generate-openapi.ts.
 */
export async function GET() {
  try {
    const filePath = join(process.cwd(), "public", "api-docs.json");
    const content = readFileSync(filePath, "utf-8");
    return new Response(content, {
      headers: {
        "Content-Type": "application/json; charset=utf-8",
        "Cache-Control": "public, max-age=3600",
        "Access-Control-Allow-Origin": "*",
      },
    });
  } catch {
    return Response.json({ error: "OpenAPI spec not found. Run: npm run docs:generate" }, { status: 404 });
  }
}
