-- AlterTable: extend DailyReport with operational metrics and scheduling metadata
ALTER TABLE "DailyReport" ADD COLUMN IF NOT EXISTS "queuedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DailyReport" ADD COLUMN IF NOT EXISTS "retriedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DailyReport" ADD COLUMN IF NOT EXISTS "timedOutCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DailyReport" ADD COLUMN IF NOT EXISTS "recoveryCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DailyReport" ADD COLUMN IF NOT EXISTS "avgExecutionMinutes" DOUBLE PRECISION;
ALTER TABLE "DailyReport" ADD COLUMN IF NOT EXISTS "activeServerCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DailyReport" ADD COLUMN IF NOT EXISTS "activeAgentCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "DailyReport" ADD COLUMN IF NOT EXISTS "generatedBy" TEXT NOT NULL DEFAULT 'manual';
ALTER TABLE "DailyReport" ADD COLUMN IF NOT EXISTS "periodStart" TIMESTAMP(3);
ALTER TABLE "DailyReport" ADD COLUMN IF NOT EXISTS "periodEnd" TIMESTAMP(3);
